import {
	Accordion,
	AccordionContent,
	AccordionItem,
	AccordionTrigger,
} from '@/components/ui/accordion'
import FadeIn from '@/components/animations/FadeIn'

const FAQS = [
	{
		question: 'Is StoryLingua suitable for beginners?',
		answer: "Absolutely. Our AI adapts to your level instantly. If you select 'Beginner (A1)', the stories will use simple vocabulary and grammar structures. As you progress, the complexity increases automatically to challenge you.",
	},
	{
		question: 'Is the content generated by AI accurate?',
		answer: "Yes. We use state-of-the-art Language Models specifically fine-tuned for education. Furthermore, every story goes through a 'Grammar Guard' layer to ensure 99.9% linguistic accuracy before it reaches your screen.",
	},
	{
		question: "How does the 'Gamification' help me learn?",
		answer: "We use the 'Spaced Repetition System' (SRS) disguised as gameplay. When you collect a 'Word Card', the game will challenge you to use it in battles (quizzes) at specific intervals calculated to maximize memory retention.",
	},
	{
		question: 'Can I use StoryLingua for free?',
		answer: "Yes! The 'Wanderer' plan is free forever, allowing you to read 3 stories per day and collect up to 50 word cards. You can upgrade to the 'Weaver' plan for unlimited access and advanced AI features.",
	},
	{
		question: "What happens if I don't understand a word?",
		answer: "Just tap on it! Unlike standard dictionaries, our Context-Engine explains the word's meaning *specifically within that sentence*, so you understand the nuance without breaking your reading flow.",
	},
]

export default function FAQSection() {
	return (
		<section className="py-24 relative z-10" id="faq">
			<div className="max-w-3xl mx-auto px-6">
				<FadeIn>
					<div className="text-center mb-16">
						<h2 className="text-3xl md:text-5xl font-bold font-outfit mb-4">
							Frequently Asked <br />
							<span className="text-transparent bg-clip-text bg-linear-to-r from-violet-400 to-fuchsia-400">
								Questions
							</span>
						</h2>
						<p className="text-gray-400">
							Everything you need to know about the Lexicon
							Alliance.
						</p>
					</div>
				</FadeIn>

				<FadeIn delay={0.2}>
					<Accordion
						type="single"
						collapsible
						className="w-full space-y-4"
					>
						{FAQS.map((faq, index) => (
							<AccordionItem
								key={index}
								value={`item-${index}`}
								className="border border-white/10 bg-white/5 rounded-xl px-6 data-[state=open]:bg-white/10 data-[state=open]:border-violet-500/30 transition-all duration-300"
							>
								<AccordionTrigger className="text-left text-lg font-medium text-gray-200 hover:text-white hover:no-underline py-6">
									{faq.question}
								</AccordionTrigger>
								<AccordionContent className="text-gray-400 leading-relaxed pb-6 text-base">
									{faq.answer}
								</AccordionContent>
							</AccordionItem>
						))}
					</Accordion>
				</FadeIn>
			</div>
		</section>
	)
}
